name: 'xmore-apr'
on: # rebuild any PRs and main branch changes
  pull_request:
  workflow_dispatch:
  push:
  schedule:
  - cron: '0 */3 * * *'

jobs:
  query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run query
        run: |
          npm install
          npm run xmore-apr 
      - name: store updated file
        run: |
          git config --global user.email "botty@example.com"
          git config --global user.name "API Bot"
          git add src/xmore-data.json
          git commit -m "Updated XMORE APR"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
